pipelines:
  default:
    - step:
        script:
          # Print the Linux version.
          - uname -a
          # Print the gcc version.
          - gcc --version
          #  Install a CMake 3.0.2 version.
          #- apt-get update -qq
          #- apt-get install cmake -y
          #  Alternatively you could install a CMake 3.2.2 version through PPA repository. 
          - apt-get update -qq
          - apt-get install software-properties-common -y
          # Add PPA repository.
          - apt-get update -qq
          - apt-get install cmake -y --force-yes
          # Print the CMake version.
          - cmake --version          
          - mkdir build
          - cd build
          # Call the CMake.
          - cmake ..
          # Build the project.
          - make
          - ./test/ExampleProject_test 
          

